[package]
name = "references-and-borrowing"
version = "0.1.0"
authors = ["micpap25 <micpap25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
